### ISSUE TITLE
Support for location, radius, result format and 'no results found' case

### ISSUE THREAD

**Issue by oyeanuj** [xuopled/react-google-places-suggest#1]
Hi @cedricdelpoux! Thank you for this library, its looks promising!
1. I was wondering if there is supports or plans to add support for location, radius and different result formats (address component types) as mentioned here: https://developers.google.com/maps/documentation/javascript/geocoding
2. How do you suggest we handle the case where no result is found in the auto-suggest? Is it possible for the input field to just take the string inputted and pass that as a value (or is that already being done?)

Thanks again!

**Comment by cedricdelpoux** [comment]
Hi @oyeanuj, sorry for the delay

1. It's a good idea to add an option to format the result. 
2. Actualy, there is no dropdown when no result is found. But you are right, I must add an option to handle this case better 

I will think about this two options and will informe you soon.

Thank you for your feedback

**Comment by oyeanuj** [comment]
Thank you, looking forward to your updates :)

**Comment by oyeanuj** [comment]
@cedricdelpoux Just checking back in to see if you had any updates here :)

**Comment by cedricdelpoux** [comment]
@oyeanuj Sorry I had a lot of work recently so I did not work on this lib. But now, I have musch free time so I will try to do that soon.

What do you expect precisely for your radius and location cases?

**Comment by oyeanuj** [comment]
@xuopled Sorry, I missed this message. To answer your question, I was just wondering if it supports the Google Places API which allows you to customize type of place, location and by radius, etc.

Any updates on the options to format the result and to handle the case of 'no results found'?

**Comment by xuopled** [comment]
I use `googleMaps.places.AutocompleteService` and `googleMaps.Geocoder` so I can use all features from these api. 

The case of 'no results found' is not so hard to add but I did not for now. I will try to add soon.

**Comment by oyeanuj** [comment]
@xuopled Thanks. For the 'no results found' case, I believe `react-geosuggest` just passes the value (optionally geocoded) to the callback function. I imagine that would be the simplest to do?

**Comment by xuopled** [comment]
@oyeanuj just published a new version. I added a `textNoResults` prop and a `renderSuggest` to let you customize the render of suggest result
