### ISSUE TITLE
Can not get postcode

### ISSUE THREAD

**Issue by dittmarconsulting** [xuopled/react-google-places-suggest#13]
Hi @xuopled,

I'm trying to get the postcode but I can not figure out how. At the moment I receive this string: `"St Kilda, Victoria, Australia"` but I need  `"St Kilda, Victoria, Australia, 3000"`

I'm using this prop `suggestTypes={['(cities)']}` to get the required info from the API , which should according to [Google's documentation](https://developers.google.com/places/web-service/supported_types#table3) either use the type `locality` or `administrative_area_level_3`. The type `postal_code` will actually return the postcode/zipcode.

There are two events fired to get the final data

1.
```
https://maps.googleapis.com/maps/api/js/GeocodeService.Search?4sSt%20Kilda%2C%20Victoria%2C%20Australia&7sUS&9sen-US&key=...
```

which returns the postcode in the `"address_components"` property of the response JSON

2.
```
https://maps.googleapis.com/maps/api/place/js/AutocompletionService.GetPredictionsJson?1sSt%20Kilda%2C%20Victoria%2C%20Australia&4sen-US&6m6&1m2&1d-0.0001796630568239043&2d-0.00017966305676964112&2m2&1d0.0001796630568239043&2d0.00017966305676964112&7scountry%3Aau&9s(cities)&15e3&key=....
```

which has no `"address_components"` property.

I'm wondering whether there is a way to incorporate this property in the final response JSON.

**Comment by dittmarconsulting** [comment]
I figured it out.

I modified your function like that:

```
    geocodeSuggest(suggestLabel, callback) {
        const {googleMaps} = this.props
        const geocoder = new googleMaps.Geocoder()
        geocoder.geocode({address: suggestLabel}, (results, status) => {
            if (status === googleMaps.GeocoderStatus.OK) {
                const location = results[0].geometry.location
                const coordinate = {
                    latitude: location.lat(),
                    longitude: location.lng(),
                    //suggestLabel
                    addressComponents: results[0].address_components,
                    formattedAddress: results[0].formatted_address
                }
                this.setState({coordinate}, callback)
            }
        })
    }
```

Instead of just assigning a string to prop`suggestLabel` I pass on the `address_components` & `formatted_address` to get the following `coordinate` object:

```
address_components: [
   0:{long_name: "Saint Kilda", short_name: "St Kilda", types: Array(2)}
   1:{long_name: "Port Phillip City", short_name: "Port Phillip", types: Array(2)}
   2:{long_name: "Victoria", short_name: "VIC", types: Array(2)}
   3:{long_name: "Australia", short_name: "AU", types: Array(2)}
   4:{long_name: "3182", short_name: "3182", types: Array(1)}
],
formattedAddress: "St Kilda VIC 3182, Australia",
latitude: -37.864,
longitude: 144.98199999999997
```

This way the user can do whatever with the returning data, which is now more useful. Why hiding info that supposed to be available to the user ;-)

**Comment by xuopled** [comment]
Good work @dittmarconsulting ! Would you like to make a PR about this ?
