### ISSUE TITLE
Set API_KEY from props?

### ISSUE THREAD

**Issue by benjick** [xuopled/react-google-places-suggest#14]
I'm only getting `API_KEY` via props, is there a way to pass that to `GoogleMapLoader`?

**Comment by xuopled** [comment]
Did you try this : 
```
const API_KEY = ...
googleMapsLoader(YourComponent, {
  libraries: ["places", "geometry"],
  key: API_KEY,
})
```

**Comment by benjick** [comment]
Yeah, but I mean the only place I have access to API_KEY is in props, like `this.props.apiKey` or whatever. Is there any way I can pass it into `googleMapsLoader` from those?

**Comment by xuopled** [comment]
I understand now. I don't know the markup to do want you want but maybe there is a way.
Nevermind, I plan to release a new version of this plugin using renderProps and not an HOC anymore. It should be ok for you after that

**Comment by benjick** [comment]
@xuopled Thank you! That sounds awesome

**Comment by xuopled** [comment]
Check out the v4.0.0 I juste release !

**Comment by xuopled** [comment]
@benjick  Check out the v4.0.0 I juste release !
