### ISSUE TITLE
textNoResults prop is not working

### ISSUE THREAD

**Issue by bogdaniy** [xuopled/react-google-places-suggest#16]
I'm trying to pass custom textNoResults property to GooglePlacesSuggest component, but no results placeholder remains unchanged.  Also, I can't find textNoResult usages in src/components/List/index.js.

**Comment by xuopled** [comment]
Thanks for reporting this. I will resolve this soon

**Comment by xuopled** [comment]
@bogdaniy Did you try `textNoResults` instead of `textNoResult` ?

**Comment by xuopled** [comment]
@bogdaniy I just release a v3.1.0 that fix the problem
