### ISSUE TITLE
Plans for React 16 update?

### ISSUE THREAD

**Issue by samatcd** [xuopled/react-google-places-suggest#17]
When using 3.1.0, under React 16 I get an error running `yarn` *incorrect peer dependency "react@^15.6.0"* and *incorrect peer dependency "react-dom@^15.6.0"*

Does this plugin support React 16, and if not, are there any plans to update it?

**Comment by xuopled** [comment]
I think it's already compatible. I just need to update dependency. Thank you for your feedback

**Comment by samatcd** [comment]
Thanks. I haven't noticed any bugs with it under React 16 so far.

**Comment by xuopled** [comment]
I just publish a new version. It should be good for you
