### ISSUE TITLE
missing css file

### ISSUE THREAD

**Issue by vzaidman** [xuopled/react-google-places-suggest#18]
i installed the latest version (3.2.1) using npm 8.9 and the pckage installed missing "lib/index.css" file

other libraries are installed with theier csses

**Comment by xuopled** [comment]
Thank you for your feedback, I will handle that

**Comment by xuopled** [comment]
Hi @vzaidman, the last version use `styled-components` so there is not generated css file. I will update the README because there is a mistake.

Thank you for your feedback.

**Comment by xuopled** [comment]
I updated it. I will close the issue. If you think the problem is still here, comment and I will reopen it.
Thank you
