### ISSUE TITLE
'This service requires an API key' despite providing in wrapper

### ISSUE THREAD

**Issue by dalenhughes** [xuopled/react-google-places-suggest#19]
I am using React 16 and the demo isn't working. It is not passing my API key to the GetPredictions API. 

https://maps.googleapis.com/maps/api/place/js/AutocompletionService.GetPredictionsJson?1ss&4sen-****omitted****&callback=_xdc_._x648s4&token=641

Here is a snippet of my package.json:
    "react": "^16.2.0",
    "react-addons-css-transition-group": "^15.6.2",
    "react-dom": "^16.2.0",
    "react-google-maps": "^9.4.1",
    "react-google-maps-loader": "^4.1.0",
    "react-google-places-suggest": "^3.2.2",

> <GoogleMapLoader

            params={{
              key: GOOGLE_API_KEY,
              libraries: "places",
            }}
            render={googleMaps =>
              googleMaps && (
                <GooglePlacesSuggest
                  googleMaps={googleMaps}
                  autocompletionRequest={{ input: search  #}}
                  onSelectSuggest={this.handleSelectSuggest.bind(this)}
                  textNoResults= "No results"
                  customRender={prediction => (
                    <div className="customWrapper">
                      {prediction
                        ? prediction.description
                        : "My custom no results text"}
                    </div>
                  )}
                >
                  <input
                    type="text"
                    value={value}
                    placeholder="Search a location"
                    onChange={this.handleInputChange.bind(this)}
                  />
                </GooglePlacesSuggest>
              )
            }
          /> 
>

**Comment by dalenhughes** [comment]
I've gotten the suggestions to work, but only by hardcoding the key into index.html

**Comment by xuopled** [comment]
No problem, enjoy !
