### ISSUE TITLE
Override styles.

### ISSUE THREAD

**Issue by zomars** [xuopled/react-google-places-suggest#23]
Is it possible? if it is, could you point me to an example?

Thank you for this library

**Comment by xuopled** [comment]
Hi @zomars, you can use `customRender` prop to override styles

**Comment by zomars** [comment]
This will let me override each individual item but not the whole list or container isn't it?

**Comment by xuopled** [comment]
right, you can style the input and each list items but not the list. I have to think about this. Do you have any ideas ?

**Comment by zomars** [comment]
Maybe pass a customListRender or customContainerRender with a the results as an array prop?

**Comment by xuopled** [comment]
Good idea. I will do as soon as I can but if you want to make a PR to make it fast, you are welcome :)

**Comment by xuopled** [comment]
@zomars Just release v3.4.0 with `customContainerRender` prop
