### ISSUE TITLE
new googleMaps.places-places is undefined

### ISSUE THREAD

**Issue by objectbb** [xuopled/react-google-places-suggest#24]
![screen shot 2018-02-23 at 10 55 38 pm 3](https://user-images.githubusercontent.com/835981/36625855-27350aae-18ed-11e8-818d-8332c018fc55.png)

**Comment by xuopled** [comment]
Hi @objectbb Thank you for reporting this. I will investigate

**Comment by xuopled** [comment]
@objectbb Can you give me more details about this bug ? I can't reproduce

**Comment by objectbb** [comment]
I think it was the result bad google map code. I decided to go with http
request.

**Comment by xuopled** [comment]
So can I close the issue ?

**Comment by objectbb** [comment]
Yes please. Thank you
