### ISSUE TITLE
Getting error

### ISSUE THREAD

**Issue by sudharsan1988** [xuopled/react-google-places-suggest#3]
Hi, I followed the instruction to do the installation but it throws 'document is not defined error' . Here is the  error log,

node_modules/react-google-places-suggest/lib/index.js:6
!function(s,u){"undefined"!=typeof e&&e.exports?e.exports=u():(o=u,r="function"==typeof o?o.call(t,n,t,e):o,!(void 0!==r&&(e.exports=r)))}("$script",function(){function e(e,t){for(var n=0,o=e.length;o>n;++n)if(!t(e[n]))return l;return 1}function t(t,n){e(t,function(e){return!n(e)})}function n(s,u,a){function l(e){return e.call?e():g[e]}function i(){if(!--v){g[y]=1,m&&m();for(var n in d)e(n.split("|"),l)&&!t(d[n],l)&&(d[n]=[])}}s=s[c]?s:[s];var f=u&&u.call,m=f?u:a,y=f?s.join(""):u,v=s.length;return setTimeout(function(){t(s,function e(t,n){return null===t?i():(t=n||-1!==t.indexOf(".js")||/^https?:\/\//.test(t)||!r?t:r+t+".js",h[t]?(y&&(p[y]=1),2==h[t]?i():setTimeout(function(){e(t,!0)},0)):(h[t]=1,y&&(p[y]=1),void o(t,i)))})},0),n}function o(e,t){var n,o=u.createElement("script");o.onload=o.onerror=o[f]=function(){o[i]&&!/^c|loade/.test(o[i])||n||(o.onload=o[f]=null,n=1,h[e]=2,t())},o.async=1,o.src=s?e+(-1===e.indexOf("?")?"?":"&")+s:e,a.insertBefore(o,a.lastChild)}var r,s,u=document,a=u.getElementsByTagName("head")[0],l=!1,c="push",i="readyState",f="onreadystatechange",g={},p={},d={},h={};return n.get=o,n.order=function(e,t,o){!function r(s){s=e.shift(),e.length?n(s,r):n(s,t,o)}()},n.path=function(e){r=e},n.urlArgs=function(e){s=e},n.ready=function(o,r,s){o=o[c]?o:[o];var u=[];return!t(o,function(e){g[e]||u[c](e)})&&e(o,function(e){return g[e]})?r():!function(e){d[e]=d[e]||[],d[e][c](r),s&&s(u)}(o.join("|")),n},n.done=function(e){n([null],e)},n})},function(t,n){t.exports=e}])})},function(e,t,n){var o;/*!

ReferenceError: document is not defined
    at /node_modules/react-google-places-suggest/lib/index.js:6:990
    at n (/node_modules/react-google-places-suggest/lib/index.js:6:59)
    at Object.t.exports (/node_modules/react-google-places-suggest/lib/index.js:6:139)
    at t (/node_modules/react-google-places-suggest/lib/index.js:1:5385)
    at Object.<anonymous> (/node_modules/react-google-places-suggest/lib/index.js:1:6121)
    at t (/node_modules/react-google-places-suggest/lib/index.js:1:5385)
    at e.__esModule.default (/node_modules/react-google-places-suggest/lib/index.js:1:5472)
    at /node_modules/react-google-places-suggest/lib/index.js:1:5477
    at n.(anonymous function).exports (/node_modules/react-google-places-suggest/lib/index.js:1:5247)
    at Object.e (/node_modules/react-google-places-suggest/lib/index.js:1:5255)
    at t (/node_modules/react-google-places-suggest/lib/index.js:1:417)
    at Object.t.exports (/node_modules/react-google-places-suggest/lib/index.js:1:1311)
    at t (/node_modules/react-google-places-suggest/lib/index.js:1:417)
    at e.__esModule.default (/node_modules/react-google-places-suggest/lib/index.js:1:504)
    at /node_modules/react-google-places-suggest/lib/index.js:1:509
    at n.(anonymous function).exports (/node_modules/react-google-places-suggest/lib/index.js:1:81)
    /tools/runServer.js:71
        throw new Error(`Server terminated unexpectedly with code: ${ code } signal: ${ signal }`);

**Comment by oyeanuj** [comment]
@sudharsan1988 Is this on the server-side? I wonder if it is related to SSR.

**Comment by xuopled** [comment]
I just published a new version. Could you check is the problem still present ?

**Comment by sudharsan1988** [comment]
@oyeanuj , yes it was on server side. I was using React Starter Kit.

@xuopled , just tried the latest version and it works awesome. Also, I must say your Google Map Loader is Brilliant :) I was able to use this for React Google Maps module too. Thank you for your wonderful work.

**Comment by xuopled** [comment]
Perfect ! Thank you for reporting this bug

**Comment by vlobrigo** [comment]
Hi. receiving an error also about google map loader especially on testing ..
it says "AutocompleteService undefined". please help. thanks.

**Comment by xuopled** [comment]
Please give me more informations about the process

**Comment by vlobrigo** [comment]
I'm testing the component and receiving this error. Do you have advise on how am I going to do the testing for this? thanks

**Comment by xuopled** [comment]
Please checkout #6 ans tell me if you can make it work.

**Comment by xuopled** [comment]
I close this issue. Feel free to reopen it if you still get the problem
