### ISSUE TITLE
no name property on response?

### ISSUE THREAD

**Issue by amlcodes** [xuopled/react-google-places-suggest#31]
am I missing something? no name property in the response

**Comment by xuopled** [comment]
What do you expect exactly? You could get everything from [geocoding google maps API](https://developers.google.com/maps/documentation/javascript/geocoding)

**Comment by amlcodes** [comment]
it was in the originalPrediction object for selectSuggest. I guess I expected it in the 1st suggestion argument as well.

**Comment by xuopled** [comment]
If I can't get the info from the Google API, I don't know what to tell to you.
