### ISSUE TITLE
Is it possible to filter by countries or cities ?

### ISSUE THREAD

**Issue by KevinAndre** [xuopled/react-google-places-suggest#32]
Hello,
I didn't find where to add filter like filter the results to show only countries or cities.
Thank you for your feedback.
Kévin

**Comment by xuopled** [comment]
Hi, you can check [AutocompletionRequest interface](https://developers.google.com/maps/documentation/javascript/reference/places-autocomplete-service?hl=fr#AutocompletionRequest) for all filters.

You can use `componentRestrictions`:
> The component restrictions. Component restrictions are used to restrict predictions to only those within the parent component. For example, the country.

**Comment by KevinAndre** [comment]
Thank you xuopled. Yes I find the answer in the code. Shame on me.
