### ISSUE TITLE
Bold font-weight disappears when using arrow keys

### ISSUE THREAD

**Issue by nmiddendorff** [xuopled/react-google-places-suggest#33]
As a user types in the input box, the options below begin to highlight the matching strings by setting the font-weight to bold. When the user uses the arrow keys 🔽 🔼  to focus an option the bold font disappears. 

![font-weight-bug-with-arrow-keys](https://user-images.githubusercontent.com/8575456/50714119-1998bb00-103d-11e9-8265-269d331933b5.gif)

**Comment by xuopled** [comment]
I published `v.3.5.1` with your fix. Thank you for your help
