### ISSUE TITLE
Pressing enter with no predictions populated does nothing

### ISSUE THREAD

**Issue by nmiddendorff** [xuopled/react-google-places-suggest#35]
I am looking to give feedback to the user that "No results were found" if they press enter when no predictions are populated. 

I would like to display custom text outside of the input box.

![fakeaddress-noresults](https://user-images.githubusercontent.com/8575456/51411991-a9eff900-1b2f-11e9-8b91-06598f7bd878.gif)

**Comment by nmiddendorff** [comment]
An idea I have for solving this would be adding a callback for no prediction to select. For example: a `onNoPredictionToSelect` function would give the developer the flexibility to perform actions necessary to communicate to the user that further action is required.

This would also give us the ability to prompt the user that nothing was entered upon enter for accessibility.

**Comment by xuopled** [comment]
Good idea. You can simply name it `onNoResult`
