### ISSUE TITLE
Dropdown Not clickable/touchable, when clicking on the white space of the item

### ISSUE THREAD

**Issue by saikatharryc** [xuopled/react-google-places-suggest#37]
![screenshot 2019-02-16 at 1 28 01 am](https://user-images.githubusercontent.com/15653282/52881349-51da0000-318a-11e9-8468-6d10dfcb00a6.png)

Currently i'm able to select the item while clicking on the Text of the dropdown element, 
but when clicking/touching in the whitespace [ right side of the text] its not working.
Not taking the click.

**Comment by xuopled** [comment]
Thank you for reporting this. I added the `help wanted` tag. If someone could make a PR to fixing this, it could be great :)

**Comment by xuopled** [comment]
I just published v3.5.2
