### ISSUE TITLE
Is there anyway we can turn off "no results found" when there is no results?

### ISSUE THREAD

**Issue by sudharsan1988** [xuopled/react-google-places-suggest#4]
I am aware that I can use textNoResults to change the "no results found" text but I would like to not to show the dropdown if there isn't any location found.

For example, if an user types an address which isn't available, it will simply behave like a textbox.

If we have an option to turn on/off this feature would be awesome :) 

Also, is there anyway I can display only the full address on the suggestion instead of generic results like "Paris, France", "Delhi, India" ...etc

Thanks again for your wonderful work.

**Comment by xuopled** [comment]
Hi @sudharsan1988 . For now there is no way to disable the "no result" but it can be added easily.

To use an other formatting you can use the `renderSuggest` prop.

The default `renderSuggest` looks like:

```
renderDefaultSuggest(suggest) {
    const {description, structured_formatting} = suggest
    const firstMatchedString = structured_formatting.main_text_matched_substrings.shift()
    let labelParts = null

    if (firstMatchedString) {
      labelParts = {
        before: description.substr(0, firstMatchedString.offset),
        matched: description.substr(firstMatchedString.offset, firstMatchedString.length),
        after: description.substr(firstMatchedString.offset + firstMatchedString.length),
      }
    }

    return (
      <div>
        <span className="placesSuggest_suggestLabel">
          {labelParts
            ? <span>
                {labelParts.before.length > 0 ? <span>{labelParts.before}</span> : null}
                <span className="placesSuggest_suggestMatch">{labelParts.matched}</span>
                {labelParts.after.length > 0 ? <span>{labelParts.after}</span> : null}
              </span>
            : description
          }
        </span>
      </div>
    )
  }
```

**Comment by sudharsan1988** [comment]
Hi @xuopled , thank you for your prompt response. As you said it was easy to hide the "No Results" text and I just sent a pull request. As it's my first pull request, please correct me if there is any mistake.

Also, I followed Custom Render function for the suggest but it keep on throwing this error,

index.js:207 Uncaught RangeError: Maximum call stack size exceeded
