### ISSUE TITLE
Input debouncing / service status callback prop

### ISSUE THREAD

**Issue by brpratt** [xuopled/react-google-places-suggest#47]
Opening this to discuss a feature request.

The callback for `getPlacePredictions` within `AutocompleteService` is given the predictions and the service status ([doc](https://developers.google.com/maps/documentation/javascript/reference/places-autocomplete-service#AutocompleteService)). At the moment, only the predictions are used.

https://github.com/xuopled/react-google-places-suggest/blob/master/src/index.js#L80

For reference, the full list of statuses are shown [here](https://developers.google.com/maps/documentation/javascript/reference/places-service#PlacesServiceStatus).

My team had an issue with using `GooglePlacesSuggest` within the context of automated tests: predictions on known good inputs would fail periodically. We modified this component to dump the service status from `getPlacePredictions` and we discovered we were receiving `OVER_QUERY_LIMIT`. Since each keystroke was sending a new prediction request (and since the automated tests type very quickly), we were hitting the rate limit on allowable requests per second.

Moving forward, it would be nice if there was...

1. Some input debouncing
2. A way to see the the service status from `getPlacePredictions`

Since the needs of input debouncing might be different for other people, I'm not sure if input debouncing belongs within this component. Debouncing in a parent component might make more sense, but I wanted to throw this out there.

For the service status, some sort of `onServiceStatus` callback prop would be nice. The `getPlacePredictions` callback could then be updated to call `onServiceStatus` with the service status. This would be helpful for debugging or for performing an action whenever we don't receive the "OK" status.

**Comment by brpratt** [comment]
Thanks @xuopled for merging #48. I think I'll close this issue unless you want to leave it open for future discussion.

**Comment by xuopled** [comment]
You can close it if your issue is resolved :)
