### ISSUE TITLE
Make geocoding optional?

### ISSUE THREAD

**Issue by tennety** [xuopled/react-google-places-suggest#50]
If I'm only interested in the result from the autocomplete, is there a way to skip the geocoding step? The only way I can think of currently is to subclass the component and override `handleSelectPrediction`. It would be nice if I could pass in a boolean prop so I can just get back the result of the selected prediction.

**Comment by xuopled** [comment]
There is no way right now but you can make a PR to add the feature

**Comment by tennety** [comment]
Haha, I ended up needing it anyway! Closing this because it seems like a small enough use case. Thank you for your hard work on this library and react-google-loader!
