### ISSUE TITLE
Testing react-google-places-suggest

### ISSUE THREAD

**Issue by vlobrigo** [xuopled/react-google-places-suggest#6]
Hi. I'm new to react especially on enzyme testing. Using the react-google-places-suggest, I was able to encounter errors like "TypeError: Cannot read property 'places' of undefined". Another is "TypeError: Cannot read property 'AutocompleteService' of undefined."  May I ask if you have any workaround/sample on testing this component? I need advise. Thanks much.

![image](https://cloud.githubusercontent.com/assets/21334758/22410889/b60d5134-e6d8-11e6-958c-823a3a482061.png)

**Comment by xuopled** [comment]
Hi, I never used Enzyme so I don't have any advices. But this component was not designed to be tested. So Google maps api is not defined in a non browser environment.

**Comment by vlobrigo** [comment]
what do you mean non-browser environment? so, what's your recommendation on this? thanks.

**Comment by xuopled** [comment]
When you use a testing tool, you are in a non browser environment. So you do not have access to `document`and `window` variables for examples.

**Comment by xuopled** [comment]
I should handle the case in my module but for now, you could exclude it in the testing yes

**Comment by Kielan** [comment]
I am also getting this err and not using typescript, but I am doing some server side rendering. The format/syntax for injecting the maps loader

```
GoogleMapLoader(MyGoogleSuggest, {
  libraries: ['places'],
  key: MY_API_KEY,
})
```

is a bit odd, how is best to poperly handle this

**Comment by xuopled** [comment]
I plan to refactor it soon

**Comment by xuopled** [comment]
Please checkout the new v3 version. 
To test the [react-google-maps-loader](https://github.com/xuopled/react-google-maps-loader), you need to add a script tag
```
beforeAll(() => {
  const script = document.createElement("script")
  document.body.appendChild(script)
})
```

**Comment by xuopled** [comment]
I close this issue. Feel free to reopen it if you still get the problem
