### ISSUE TITLE
Cannot get 'suggestComponentRestrictions' to work

### ISSUE THREAD

**Issue by Samulionis** [xuopled/react-google-places-suggest#9]
Hi, 

I'm trying to limit searches to the city names, as I understood 'suggestComponentRestrictions' could do the work.  

I tried with countries.

const country = {country: 'fr'};

<GooglePlacesSuggest
  suggestComponentRestrictions={country}
>
</GooglePlacesSuggest>

It doesnt seems to work, is there are something wrong I'm doing? And Google Api accepts (region) parameter wich should restrict result to city names. Can it be used with suggestComponentRestrictions?

**Comment by sudharsan1988** [comment]
Make sure you use the latest version - 2.1.1 and you can use like the below code,

```
const suggestComponentRestrictions = {
      country: "us"
    };
<GooglePlacesSuggest
suggestComponentRestrictions={suggestComponentRestrictions}
/>
```

That should work.

**Comment by xuopled** [comment]
@Samulionis Do the solution above work for you?
